#!/bin/sh

set -e

BACKUP_PREFIX=${BACKUP_PREFIX:-backup}
BACKUP_DEST_FOLDER=${BACKUP_DEST_FOLDER:-/var/tmp/}
BACKUP_FIND_OPTIONS=${BACKUP_FIND_OPTIONS:?"BACKUP_FIND_OPTIONS are required"}
BACKUP_DELETE_LOCAL_COPY=${BACKUP_DELETE_LOCAL_COPY:-true}

BACKUP_AWS_KEY=${BACKUP_AWS_KEY:-}
BACKUP_AWS_SECRET=${BACKUP_AWS_SECRET:-}
BACKUP_AWS_S3_PATH=${BACKUP_AWS_S3_PATH:-}

# upload to amazon s3
if [[ ${BACKUP_MYSQL} ]]; then
    # Make the mysqldump

    now=$(date +"%s_%Y-%m-%d")
    BACKUP_NAME = "/tmp/${now}_mysqldump.sql.gz"
    /usr/bin/mysqldump --opt -h ${MYSQL_HOST} -u ${MYSQL_USER} -p${MYSQL_PASSWORD} --all-databases | gzip > ${BACKUP_NAME}

    # upload to S3
    s3cmd \
        --access_key="${BACKUP_AWS_KEY:?'BACKUP_AWS_KEY is required'}" \
        --secret_key="${BACKUP_AWS_SECRET:?'BACKUP_AWS_SECRET is required'}" \
        put ${BACKUP_NAME} \
        "${BACKUP_AWS_S3_PATH}"

    # remove the backup locally
    rm ${BACKUP_NAME}
    
elif [[ ${BACKUP_AWS_S3_PATH} ]]; then
    s3cmd \
        --access_key="${BACKUP_AWS_KEY:?'BACKUP_AWS_KEY is required'}" \
        --secret_key="${BACKUP_AWS_SECRET:?'BACKUP_AWS_SECRET is required'}" \
        sync -r "${BACKUP_FIND_OPTIONS}" \
        "${BACKUP_AWS_S3_PATH}"
fi

